#### Mapping Functions ####
## Version 3.1
# Started: 14 July 2021
# Last worked on: 14 July 2021
# Author: Clay Meredith
# File: Dependent_scripts/map_build.R
# Description: Script uses mapping data generated by LC_pipeline_main.R to display
#              maps to the user. A separate script will be used to open mapped data.

#### TODO ####

#### Set Working Directory ####
if (!exists("current.dir")){
  current.dir <- dirname(parent.frame(2)$ofile)
  setwd(current.dir)
  print(getwd())
}

GBIF_toggle <- "Y"

# Load base functions
source("Back_end/Dependent_scripts/base_functions.R")
# Load dependent data
source("Back_end/Dependent_scripts/data_load.R")

#### Load packages and dependencies ####
packages <- c("ggplot2","sf","tmap","tidyverse","dplyr","RColorBrewer")

lapply(packages, package.check)

#### Main Mapping Function ####
MAPPER_MAIN <- function (){
  # Prompt user to choose data source
  selected_action <- choose_map_source()
  if(selected_action == "Choose previous batch results"){
    map_batch_load()
  } else {
    species_processing(spec.list, countries_table, point_data)
  }
}  

#### Dependent Functions ####

# Parameters: None
# Returns: selected_action
# Throws: none
# Purpose: Prompts user to select data source for map.

choose_map_source <- function (){
  # Prompt user to select action
  selected_action <- select.list(c("Choose previous batch results",
                                   "Continue with current batch"
                                   ), 
                                  preselect = NULL, multiple = FALSE,
                                  title = "Select data source",
                                  graphics = getOption("menu.graphics"))
  return(selected_action)
}

# Parameters: None
# Returns: batch (character)
# Throws: none
# Purpose: Prompts user to choose batch number for data to load.
map_batch_choice <- function (){
    # Pull existing file names
    batches <- list.files(path = "Outputs/", pattern = "species_inputs")
    batches <- unlist(lapply(batches, function (x){
      substr(x, 22,33)
    }
    )
    )
    batch <- select.list(batches, 
                preselect = NULL, multiple = FALSE,
                title = "Select batch",
                graphics = getOption("menu.graphics"))
    return(batch)
  }

# Parameters: None
# Returns: spec.list, countries, point_data
# Throws: none
# Purpose:
map_species_load <- function (x) {
  
  spec.list <- list.files(path = "Outputs/", pattern = paste("species_inputs_batch_", 
                                                x, sep = ""))
  spec.list <- data.frame(read.csv(file = paste("Outputs/",spec.list, sep = "")))
  return(spec.list)
}

map_countries_load <- function (x) {
  
  countries_table <- list.files(path = "Outputs/", pattern = paste("Countries_batch_", 
                                                             x, sep = ""))
  countries_table <- data.frame(read.csv(file = paste("Outputs/",countries_table, sep = "")))
  return(countries_table)
}

map_points_load <- function (x) {
  
  point_data <- list.files(path = "Outputs/", pattern = paste("Point_data_batch_", 
                                                                   x, sep = ""))
  point_data <- data.frame(read.csv(file = paste("Outputs/",point_data, sep = "")))
  return(point_data)
}

# Parameters: None
# Returns: selected_species (id number for chosen species)
# Throws: none
# Purpose: Allows user to select species to display map

species_select <- function (x){
  # Prompt user to select species
  selected_species <- select.list(x$Species, 
                                  preselect = NULL, multiple = FALSE,
                                  title = "Select species for map display",
                                  graphics = getOption("menu.graphics"))
  
  selected_species <- x$id[which(x$Species == selected_species)]
  return(selected_species)
}

# Parameters: selected_species
# Returns: 
# Throws: none
# Purpose: Subset countries_table with species results to pass on to
#          tm_fill
countries_table_subset <- function (x,y){
  species_dist <- y[which(y$id == x),]
  return(species_dist)
}

# Parameters: selected_species
# Returns: 
# Throws: none
# Purpose: Subset points_table with species results to pass on to
#          tm_fill
point_data_subset <- function (x,y){
  point_data <- y[which(y$ID_NO == x),]
  return(point_data)
}

# Parameters: species_dist
# Returns: 
# Throws: none
# Purpose: Add occurrence data to species_dist table
countries_table_append <- function(x){
  # Add occurrence data to species_dist table
  x$occ <- occ.codes$lvl3_display[
    match(x$occ, occ.codes$iucn_code)]
  # Rename columns for join
  names(x) <- c("id","ORIGIN","PRESENCE",
                "SEASONALITY","lvl3_display")
  # Convert to tibbles for join
  x <- as_tibble(x)
  occ.codes <- as_tibble(occ.codes)
  # Perform join
  x <- left_join(occ.codes,x,by = "lvl3_display")
  # Convert to data frame
  x <- data.frame(x)
  # Return results
  return(x)
}
# Parameters: species_dist
# Returns: lvl3
# Throws: none
# Purpose: Adds origin column to lvl3 table for final output display
origin_column_build <- function (x){
  # Build origin column and populate with origin values from species_dist
  lvl3$origin <- x$ORIGIN[match(lvl3$LEVEL3_COD,x$lvl3_display)]
  # Replace NA values with 0
  lvl3$origin[which(is.na(lvl3$origin))] <- 0
  foo <<- lvl3
  return(lvl3)
}

# Parameters: lvl3
# Returns: range_map
# Throws: none
# Purpose: Builds map for display
map_builder <- function (x,y){
  # Build palette
  cust.palette <- c("#d9d9d9",brewer.pal(n=6, name = "Accent"))
  # Build base polygon
  range_map <- tm_shape(x,
                        title.col="Regional Origin")
  # Shade according to origin
  range_map <- range_map + tm_fill(col = "origin", 
                                   palette = cust.palette,
                                   style = "fixed",
                                   breaks = c(0:7),
                                   legend.show = FALSE,
                                   # labels = c("Not present",
                                   #            "1",
                                   #            "2",
                                   #            "3",
                                   #            "4",
                                   #            "5",
                                   #            "6")
                                   )
  # Add borders
  range_map <- range_map + tm_borders()
  # Add points
  range_map <- range_map + tm_shape(y) + 
    tm_dots(col = "ORIGIN",
            palette = cust.palette,
            style = "fixed",
            breaks = c(0:7),
            labels = c("Not present",
                       "1",
                       "2",
                       "3",
                       "4",
                       "5",
                       "6"),
            # title.col = "Point Origin",
            popup.vars=c("Specimen year"="EVENT_YEAR",
                         "Subspecies"="SUBSPECIES",
                         "Subpopulation"="SUBPOP",
                         "Catalog Number"="CATALOG_NO",
                         "Source"="SOURCE",
                         "Origin"="ORIGIN")
            )
  print("Drawing map")
  return(range_map)
}

# Parameters: 
# Returns: 
# Throws: 
# Purpose:
map_batch_load <- function (){
  # Prompt user to choose batch
  map_batch_number <- map_batch_choice()
  # Load data if necessary
  spec.list <<- map_species_load(map_batch_number)
  countries_table <<- map_countries_load(map_batch_number)
  point_data <<- map_points_load(map_batch_number)
  # Proceeed to species processing
  species_processing(spec.list, countries_table, point_data)
}

# Parameters: spec.list (x), countries_table (y), point_data (z)
# Returns: 
# Throws: 
# Purpose: Bundles species processing from selection to data processing
species_processing <- function (x,y,z){
  # Prompt user for species select
  selected_species <- species_select(x)
  # Subset countries table
  species_dist <- countries_table_subset(selected_species,y)
  species_dist <- countries_table_append(species_dist)
  # Subset point data
  point_data <- point_data_subset(selected_species, z)
  # Convert point data to sf
  point_data <- sf.function(point_data)
  # Build origin column for lvl3 table
  lvl3 <- origin_column_build(species_dist)
  # Build map
  final_map <- map_builder(lvl3, point_data)
  return(final_map)
}

# Set tmap to interactive mode
tmap_mode("view")
#### Run main ####
MAPPER_MAIN()
# Remove dummy toggle (holdover from borrowed code)
rm(GBIF_toggle)
